#include <stdio.h>
#include <stdlib.h>

int diagonalCheck(int array[100][100],int x1,int y1, int x2,int y2)
{
    int a,b,c;
    int tempx,tempy;
    a=y2-y1;
    b=x2-x1;
    c=-b*y1-a*x1;
    tempx=x1;
    if(x1<x2)
    {
        while(tempx<x2)
        {

            tempx++;
        }
    }
    else
    {
        if(x1==x2)
        {
            tempy=y1;
            i=y2;
            if(i<tempy)
            {
                while(i<tempy)
                {
                    if(array[x1][i]==0)
                    {
                        break;
                    }
                    i++;
                }
            }
            else
            {
               while(i>tempy)
                {
                    if(array[x1][i]==0)
                    {
                        break;
                    }
                    i--;
                }
            }
        }
        else
        {

            while(tempx>x2)
            {
                tempx--;
            }
        }
    }
    tempy=y1;
    if(y1<y2)
    {
        while(tempy<y2)
        {
            tempy++;
        }
    }
    else
    {
        if(y1==y2)
        {
            tempx=x1;
            i=x2;
            if(i<tempx)
            {
                while(i<tempx)
                {
                    if(array[i][y1]==0)
                    {
                        break;
                    }
                    i++;
                }
            }
            else
            {
               while(i>tempx)
                {
                    if(array[i][y1]==0)
                    {
                        break;
                    }
                    i--;
                }
            }
        }
        else
        {
            while(y1>y2)
            {
                y1--;
            }
        }
    }
    return 1;
}

int main()
{
    int floor[100][100];
    int visibility[100][100];
    int vertices;
    int x,y;
    int tempvertices;
    int i,k,l,m;
    int first;
    scanf("%d",&vertices);
    while(vertices!=0)
    {
        i=k=0;
        while(i<100)
        {
            while(k<100)
            {
                visibility[i][k]=0;
                k++;
            }
            k=0;
            l++;
        }
        tempvertices=vertices;
        while(tempvertices>0)
        {
            scanf("%d",&x);
            scanf("%d",&y);
            if(floor[i][k]==42||floor[i][k]==2)
            {
                floor[x][y]=42;
                tempvertices--;
            }
            i=k=l=0;
            first=0;
            while(i<10)
            {
                while(k<10)
                {
                    if(first==1&&floor[i][k]==42)
                    {
                        first=0;
                        printf("-");
                        k++;
                        continue;
                    }
                    if(first==1&&floor[i][k]!=42)
                    {
                        printf(".");
                        floor[i][k]=2;
                        k++;
                        continue;
                    }
                    if(first==0&&floor[i][k]==42)
                    {
                        first=1;
                        printf("-");
                        k++;
                        continue;
                    }
                    if(first==0&&floor[i][k]!=42)
                    {
                        printf("*");
                        floor[i][k]=0;
                        k++;
                        continue;
                    }

                }
                printf("\n");
                l=0;
                first=0;
                k=0;
                i++;
            }
            i=k=l=m=0;
            while(i<100)
            {
                while(k<100)
                {
                    if(floor[i][k]==42||floor[i][k]==2)
                    {
                        while(l<100)
                        {
                            while(m<100)
                            {
                                if(floor[i][k]==42||floor[i][k]==2)
                                {
                                    if(diagonalCheck(floor,i,k,l,m))
                                    {
                                        visibility[i][k]++;
                                    }
                                }
                                m++;
                            }
                            m=0;
                            l++;
                        }
                    }
                    k++;
                }
                k=0;
                i++;
            }
            i=k=0;
            while(i<10)
            {
                while(k<10)
                {
                    floor[i][k]=0;
                    k++;
                }
                k=0;
                i++;
            }
            scanf("%d",&vertices);
        }
        return 0;
    }
